version: '3'

services:


  GestionStationSki:
    container_name: gestionStationSki
    build: ./
    ports:
      - "8089:8089"
    hostname: gestionStationSki
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_4:3306/stationSki?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    image: "projetdevops/projet"
    depends_on:
      - docker-mysql_4



  docker-mysql_4:
    container_name: mysql4
    image: mariadb:10.4.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"